import { StyleSheet } from 'react-native';
import { colors } from './colors';

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.black,
    padding: 20,
  },
  brutalistCard: {
    backgroundColor: colors.darkGray,
    borderWidth: 3,
    borderColor: colors.neonGreen,
    borderRadius: 0,
    padding: 20,
    marginVertical: 10,
    shadowColor: colors.neonGreen,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
    elevation: 10,
  },
  brutalistButton: {
    backgroundColor: colors.black,
    borderWidth: 3,
    borderColor: colors.neonPink,
    borderRadius: 0,
    paddingHorizontal: 30,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 10,
  },
  brutalistButtonText: {
    color: colors.neonPink,
    fontSize: 18,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 2,
    textShadowColor: colors.neonPink,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  brutalistInput: {
    backgroundColor: colors.darkGray,
    borderWidth: 2,
    borderColor: colors.neonBlue,
    borderRadius: 0,
    padding: 15,
    color: colors.white,
    fontSize: 16,
    marginVertical: 10,
  },
  neonText: {
    color: colors.neonGreen,
    fontSize: 24,
    fontWeight: 'bold',
    textShadowColor: colors.neonGreen,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  balanceText: {
    color: colors.bitcoin,
    fontSize: 32,
    fontWeight: 'bold',
    textAlign: 'center',
    textShadowColor: colors.bitcoin,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 15,
  },
});